---
# Install the library files that php7 depends on
# 2018-04-04 19:34 by liubaobao at WDTY company


- name: Install Packages Needed To Compile PHP 7
  apt: name={{ item }} state=latest
  with_items:
    - autoconf
    - libpcre3-dev
    - libssl-dev
    - libxml2-dev
    - libcurl4-openssl-dev
    - libbz2-dev
    - libjpeg8-dev
    - libpng++-dev
    - libfreetype6-dev
    - libmcrypt-dev
    - libmemcached-dev
    - libgearman-dev
    - libmagickwand-dev
    - libmagickcore-dev
    - libevent-dev
  tags: compile
