---
#Install yar extension for php
#2018-04-06 12:07 by liubaobao at WDTY company


- name: Load yar extend
  command: /home/yx/server/php7/bin/phpize
  args:
    chdir: /tmp/{{ YAR }}/

- name: Configure the build
  command: ./configure --with-php-config=/home/yx/server/php7/bin/php-config
  args:
    chdir: /tmp/{{ YAR }}/

- name: Build yar extend
  command: make -j
  args:
    chdir: /tmp/{{ YAR }}/

- name: Install yar extend
  command: make install
  args:
    chdir: /tmp/{{ YAR }}/
