---
# tasks file for php7_or_php54_install
# 2018-04-04 23:28 by liubaobao at WDTY company


- include: sync_php7_source_code.yml
- include: compile_package_install_forphp7.yml
- include: decompression_source_package.yml
- include: php_install.yml
- include: install_memcached_extend.yml
- include: install_redis_extend.yml
- include: install_swoole_extend.yml
- include: install_yaf_extend.yml
- include: install_yar_extend.yml
- include: sync_conf.yml
- include: restart_phpfpm.yml

