---
# Perform source code compilation and installation php7
# 2018-04-04 19:54 by liubaobao at WDTY company


- name: Create a few install directories
  file: path=/home/yx/server/php7/{{ item }} recurse=true state=directory
  with_items:
    - log
  ignore_errors: True
  tags: createdir

- name: Configure the build.
  command: ./configure {{ PHPCONFIGURE }}
  args:
    chdir: /tmp/{{ PHP7 }}/

- name: Build PHP7
  command: make -j
  args:
    chdir: /tmp/{{ PHP7 }}/

- name: Install PHP7
  shell: make install
  args:
    chdir: /tmp/{{ PHP7 }}/
