---
# Publisher synchronization php7 source package and extend packages to the installation remote machine
# 2018-04-04 19:28 by liubaobao at WDTY company


- name: Unarchive PHP7 Sorce Code to Remote Machice
  copy: src={{ PHP7 }}.tgz dest=/tmp/{{ PHP7 }}.tgz
  ignore_errors: True
  tags: syncphp7

#Extension pack for php7 memcached
- name: Unarchive PHP7 memcached extend package to Remote Machice
  copy: src={{ MEMCACHED }}.tgz dest=/tmp/{{ MEMCACHED }}.tgz
  ignore_errors: True
  tags: syncmemcached

#Extension pack for php7 redis
- name: Unarchive PHP7 redis extend package to Remote Machice
  copy: src={{ REDIS }}.tgz dest=/tmp/{{ REDIS }}.tgz
  ignore_errors: True
  tags: syncredis

#Extension pack for php7 ssh2
- name: Unarchive PHP7 ssh2 extend package to Remote Machice
  copy: src={{ SSH2 }}.tgz dest=/tmp/{{ SSH2 }}.tgz
  ignore_errors: True
  tags: syncssh2

#Extension pack for php7 ssh2
- name: Unarchive PHP7 swoole extend package to Remote Machice
  copy: src={{ SWOOLE }}.tgz dest=/tmp/{{ SWOOLE }}.tgz
  ignore_errors: True
  tags: syncswoole

#Extension pack for php7 ssh2
- name: Unarchive PHP7 swoole extend package to Remote Machice
  copy: src={{ YAF }}.tgz dest=/tmp/{{ YAF }}.tgz
  ignore_errors: True
  tags: syncyaf

#Extension pack for php7 ssh2
- name: Unarchive PHP7 swoole extend package to Remote Machice
  copy: src={{ YAR }}.tgz dest=/tmp/{{ YAR }}.tgz
  ignore_errors: True
  tags: syncyar
